version: '3.8'

services:
  llama-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - CMAKE_ARGS=-DLLAMA_CUBLAS=ON
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]



