version: '3.3'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    command: uvicorn api:app --host 0.0.0.0 --port 80 --reload
  llm:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app
